name: Release GitHub Actions With Some Inputs

on:
  workflow_call:
    inputs:
        excludeOptions:
          type: string
          description: Separate the files or folders that you do not want to see in the release with a comma. 
          required: false
        zipName:
          type: string
          description: Given release zip name
          required: true
        web:
          type: boolean
          description: If the value is true then it builds web files, if not then it is a simple release.
          required: false
jobs:
  create-release:
    name: Build and Create Tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: 'Setup node'
        uses: actions/setup-node@v3
        with:
          node-version: 17
          
      - name: Install dependencies
        if: inputs.web
        run: npm i
        working-directory: web

      - name: Run build
        if: inputs.web
        run: npm run build
        working-directory: web
        env:
          CI: false
                  
      - name: Download Bump manifest version js file and run in node
        run: curl -f https://raw.githubusercontent.com/CommunityRP-FiveM-Server/.github/961b50cd10fdda968a7a8a4b78af5fd2447cf650/.github/actions/bump-manifest-version.js | node -
        env:
          TGT_RELEASE_VERSION: ${{ github.ref_name }}

      - name: Push manifest change
        uses: EndBug/add-and-commit@v8
        with:
          add: fxmanifest.lua
          push: true
          author_name: Manifest Bumper
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: bump manifest version to ${{ github.ref_name }}'

      - name: Update tag ref
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{ github.ref_name }}

      - name: Create exclude file from input
        run: |
         IFS=',' read -ra ADDR <<< "${{ inputs.excludeOptions }}"
          for i in "${ADDR[@]}"; do
            echo "${i// /}" >> exclude.txt
          done

      - name: Bundle web files
        if: inputs.web
        run: |
          mkdir -p ./temp/${{ inputs.zipName }}
          mkdir -p ./temp/${{ inputs.zipName }}/web
          cp -r ./web/dist ./temp/${{ inputs.zipName }}/web/dist
          
      - name: Bundle files
        run: |
          mkdir -p ./temp/${{ inputs.zipName }}
          
          if [[ -f exclude.txt ]]; then
            rsync -av --progress --exclude=temp/ --exclude-from=exclude.txt --exclude=exclude.txt ./ ./temp/${{ inputs.zipName }}/
          elif [[ "${{ inputs.web }}" == "true" ]]; then
            rsync -av --progress --exclude=temp/ --exclude=.git --exclude=.github --include=web/dist/** --exclude=web/** ./ ./temp/${{ inputs.zipName }}/
          else
            rsync -av --progress --exclude=temp/ --exclude=.git --exclude=.github ./ ./temp/${{ inputs.zipName }}/
          fi
          
          cd ./temp && zip -r ../${{ inputs.zipName }} ./${{ inputs.zipName }}/
          
      - name: Create Release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        id: auto_release
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: '${{ env.RELEASE_VERSION }}'
          prerelease: false
          files: ${{ inputs.zipName }}.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
