name: Simple Release GitHub Actions

on:
  workflow_call:
    inputs:
        excludeOptions:
          type: string
          description: Separate the files or folders that you do not want to see in the release with a comma. 
          required: false
        zipName:
          type: string
          description: Given release zip name
          required: true
        web:
          type: string
          description: If the value is true then it builds web files, if not then it is a simple release.
          required: false
        versionNumber:
          type: string
          description: If the value is true then it builds web files, if not then it is a simple release.
          required: false
jobs:
  create-release:
    name: Build and Create Tagged release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      
    steps:
      - name: Convert 'web' input to boolean and set as env var
        run: |
          if [ "${{ inputs.web }}" = "true" ]; then
            echo "WEB=true" >> $GITHUB_ENV
          else
            echo "WEB=" >> $GITHUB_ENV
          fi
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Setup node with dependency path
        if: ${{ env.WEB }}
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
          
      - name: Install dependencies
        if: ${{ env.WEB }}
        run: npm i
        working-directory: web

      - name: Run build
        if: ${{ env.WEB }}
        run: npm run build
        working-directory: web
        env:
          CI: false
          
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
      - name: Get next minor version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Create new milestone
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.semvers.outputs.patch }}
      - name: Set Release Version
        id: set_version
        run: |
          if [ "${{ inputs.versionNumber }}" != "" ]; then
            echo "DETERMINED_VERSION=${{ inputs.versionNumber }}" >> $GITHUB_ENV
          else
            echo "DETERMINED_VERSION=${{ steps.semvers.outputs.patch }}" >> $GITHUB_ENV
          fi
      - name: 'Download Bump manifest version js file and run in node'
        run: curl -f https://raw.githubusercontent.com/esx-framework/.github/main/.github/actions/bump-manifest-version.js | node -
        env:
          TGT_RELEASE_VERSION: ${{ env.DETERMINED_VERSION }}
      - name: Push manifest change
        uses: EndBug/add-and-commit@v8
        with:
          add: fxmanifest.lua
          push: true
          author_name: Manifest Bumper
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: bump manifest version to ${{ env.DETERMINED_VERSION }}'

      - name: Update tag ref
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{ env.DETERMINED_VERSION }}

      - name: Create exclude file from input
        run: |
         IFS=',' read -ra ADDR <<< "${{ inputs.excludeOptions }}"
          for i in "${ADDR[@]}"; do
            echo "${i// /}" >> exclude.txt
          done

      - name: Bundle web files
        if: ${{ env.WEB }}
        run: |
          mkdir -p ./temp/${{ inputs.zipName }}
          mkdir -p ./temp/${{ inputs.zipName }}/web
          cp -r ./web/dist ./temp/${{ inputs.zipName }}/web/dist
          
      - name: Bundle files
        run: |
          mkdir -p ./temp/${{ inputs.zipName }}
          
          if [[ -f exclude.txt ]]; then
            rsync -av --progress --exclude=temp/ --exclude-from=exclude.txt --exclude=exclude.txt --exclude=.git --exclude=.github ./ ./temp/${{ inputs.zipName }}/
          elif [[ "${{ env.WEB }}" == "true" ]]; then
            rsync -av --progress --exclude=temp/ --exclude=.git --exclude=.github --include=web/dist/** --exclude=web/** ./ ./temp/${{ inputs.zipName }}/
          else
            rsync -av --progress --exclude=temp/ --exclude=.git --exclude=.github ./ ./temp/${{ inputs.zipName }}/
          fi
          
          cd ./temp && zip -r ../${{ inputs.zipName }} ./${{ inputs.zipName }}/
          
      - name: Create Release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        id: auto_release
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: ${{ env.DETERMINED_VERSION }}
          prerelease: false
          files: ${{ inputs.zipName }}.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
